apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-demo-pod
  name: nginx
spec:
  containers:
  - image: nginx:1.12.2
    imagePullPolicy: IfNotPresent
    name: nginx
    resources:
      limits:
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 70Mi
    ports:
    - containerPort: 80
      protocol: TCP
  dnsPolicy: ClusterFirst
  restartPolicy: Always