apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-volume-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-volume-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deployment-volume-demo
    spec:
      containers:
      - image: nginx:1.12.2
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
          protocol: TCP
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        volumeMounts: 
        - mountPath: /usr/share/nginx/html
          name: hello
      volumes: 
      - gitRepo:
          repository: https://github.com/linc101/helloFromHangzhou.git
          directory: helloFromHangzhou
        name: hello
